### ISSUE TITLE
Frage dazu

### ISSUE THREAD

**Issue by Just2Confuse** [nevakee/tibber-grafana#1]
Hi,

kann man das irgendwie debuggen? Ich hab nen Tibber Pulse der in Home Assi auch ausgelesen wird. In Grafana + Dashboard + Datenquelle passiert nicht viel. Meine Daten (Adresse usw) werden ausgelesen, aber es kommen keine Verbrauchsdaten an. 

Hast Du vielleicht eine Idee? Ich hab keinen Stromvertrag bei denen, nur den Tibber Pulse. Aber das sollte kein Hinderungsgrund sein. Läuft seit gestern. 
![Screenshot 2024-03-22 082607](https://github.com/nevakee/tibber-grafana/assets/140651588/67b08cde-bde0-497a-a309-b968e9022746)

**Comment by nevakee** [comment]
Hi,
soweit wie ich weiß, werden ohne Stromvertrag keine Daten, wie z.B. Verbrauch bei Tibber gespeichert. Das Dashboard ruft alle Daten immer nur von der Tibber API ab. Wenn also in der Tibber Smartphone App keine Daten (Stromrpeis, Verbrauch, etc) zusehen sind, dann wird bei Grafana auch nichts angezeigt.

**Comment by Just2Confuse** [comment]
Hmmm, OK. In Home Assi kommen die Daten zumindest rein. Macht nix, dann lass ich das per Grafana. Ist ja nicht Deine "Schuld" :)
