### ISSUE TITLE
Keine Daten mit Grafana Version 11

### ISSUE THREAD

**Issue by weindler** [nevakee/tibber-grafana#2]
Hi, habe mich nach deiner Anleitung gehalten, aber es kommen keine Daten rein.

![Tibber api Infinity](https://github.com/nevakee/tibber-grafana/assets/41335851/a6b5b65f-f8b3-419d-b521-ac0de154ebe6)

Habe die Grafan Version [Grafana v11.0.0 (277ef258d4)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)

Danke vorab für deine Hilfe und für deine bereits geleistete Arbeit.

**Comment by nevakee** [comment]
Hi, 
wenn keine Daten angezeigt werden, kannst du mal probieren, ein Panel zubearbeiten und unter Query inspector gucken, ob dort eine brauchbare Fehlermeldung erscheint.

Hier ein Beispiel:
<img width="1709" alt="grafik" src="https://github.com/nevakee/tibber-grafana/assets/38612922/c52df300-1c99-4c77-9db9-bc87037a0bec">

**Comment by weindler** [comment]
So, nun läuft es, war ich wohl zu voreilig, man musste ein wenig abwarten, danke dir, wünsche schönen Restsonntag

**Comment by weindler** [comment]
Closed
