### ISSUE TITLE
Kosten aktuelle Stunde

### ISSUE THREAD

**Issue by Just2Confuse** [nevakee/tibber-grafana#3]
Hi,

ist es möglich das bei den letzten "Tibber Exporter" Updates irgendwas anders war? Ich weiß leider nicht wie ich an die Datenquellen etc herankomme um vielleicht mehr Daten zu liefern. Die restlichen Felder scheinen alle normal zu sein. 
![tibber](https://github.com/nevakee/tibber-grafana/assets/140651588/9722f1a4-da07-444e-adeb-70558d77c6c3)

Viele Grüße und Danke sehr

**Comment by nevakee** [comment]
Hi,
wie bereits in der Beschreibung geschrieben, werden alle Daten live von der Tibber API geladen. Es wird also nichts "exportiert" oder irgendwo zwischengespeichert.
Werden den die Kosten und Verbrauch der letzten Stunden in der App angezeigt?

**Comment by Just2Confuse** [comment]
OK. Dann hab ich das Konstrukt evtl falsch verstanden. Ich dachte der Exporter ist ne Art Hypervisor/Zwischenschicht der die Datenbank füttert. Aktuell ist es schlicht leer. Ich warte mal weiter.

**Comment by Just2Confuse** [comment]
PS: Hat sich erledigt. Das Stundenmodel scheint arg anfällig zu sein. Mal haben wir Werte und mal nicht. Ihr könnt das Issue gerne löschen.
