### ISSUE TITLE
High request rate towards Tibber API

### ISSUE THREAD

**Issue by jstaro** [nevakee/tibber-grafana#4]
Hi,

Us at Tibber noticed that we see quite a high volume of requests from the user-agent `Grafana/9.4.3`.
I believe it might be this component that is being used.

I see that it uses the [Infinity](https://grafana.com/docs/plugins/yesoreyeram-infinity-datasource/latest/) data source. It appears there is no way to set a refresh/rate limit in the plugin, so it is causing a lot of unnecessary load on our API, and resulting in users of this plugin probably receiving a lot of `429 Too Many Requests` rate limit responses, which is a poor Tibber customer experience, especially if you use several integrations towards the Tibber API.

Infinity seems to poll once every second. There is no data in the Tibber API that refreshes that fast, so there really is no good reason for doing this, but I realize that it's very convenient to use this data source.

Would it be possible to look into using another, more configurable data source so users of this component do not get rate limited? I could help look into an alternative if you do not know of one.

**Comment by nevakee** [comment]
Hi jstaro,

I am currently not a Tibber customer and therefore no longer use the dashboard. 
I will also no longer maintain the dashboard (No access to the Tibber API).

However, I can say that I had no problems with the rate limit, unless I refresh the dashboard too many times within 5 minutes. The default refresh interval for the dashboard is 1 hour.

**Comment by jstaro** [comment]
Alright! Seems like I should look around elsewhere. Not really anything you can do here.
Thanks for your time.
